stages:
  - build
  - test
  - deploy   

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
  JAR_NAME: "indian_flavor_scape-0.0.1-SNAPSHOT.jar"
    
build:
  stage: build
  script:
    - cd Indian-Flavor-Scape/Back-End/indian_flavor_scape
    - gradle build
  artifacts:
    paths:
      - Indian-Flavor-Scape/Back-End/indian_flavor_scape/build/libs/$JAR_NAME
 
test:
  stage: test
  script:
    - cd Indian-Flavor-Scape/Back-End/indian_flavor_scape
    - gradle test
  allow_failure: false
    
deploy:
  stage: deploy
  environment:
    name: localhost 
    url: http://localhost:8080
  script:
    - cd Indian-Flavor-Scape/Back-End/indian_flavor_scape/build/libs
    - java -jar $JAR_NAME
    - while ! curl -s http://localhost:8080/IndianFlavorScape/menu/getMainDishes >/dev/null; do sleep 5; done